// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID           int64
	Manufacturer string
	Model        string
	BuildNumber  string
	Os           string
	ScreenWidth  int64
	ScreenHeight int64
}

type Telemetry struct {
	ID         int64
	UserID     uuid.UUID
	DeviceID   int64
	OsVersion  string
	AppVersion string
	Action     string
	Data       []byte
	Timestamp  time.Time
}

type User struct {
	ID uuid.UUID
}

type UserDevice struct {
	UserID   uuid.UUID
	DeviceID int64
}
