// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: telemetries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertTelemetry = `-- name: InsertTelemetry :execresult
INSERT INTO telemetries (user_id, device_id, os_version, app_version, action, data, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertTelemetryParams struct {
	UserID     uuid.UUID
	DeviceID   int64
	OsVersion  string
	AppVersion string
	Action     string
	Data       []byte
	Timestamp  time.Time
}

func (q *Queries) InsertTelemetry(ctx context.Context, arg InsertTelemetryParams) (sql.Result, error) {
	return q.exec(ctx, q.insertTelemetryStmt, insertTelemetry,
		arg.UserID,
		arg.DeviceID,
		arg.OsVersion,
		arg.AppVersion,
		arg.Action,
		arg.Data,
		arg.Timestamp,
	)
}
