// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user_devices.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertUserDeviceIfNotExists = `-- name: InsertUserDeviceIfNotExists :execresult
INSERT INTO user_devices (user_id, device_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type InsertUserDeviceIfNotExistsParams struct {
	UserID   uuid.UUID
	DeviceID int64
}

func (q *Queries) InsertUserDeviceIfNotExists(ctx context.Context, arg InsertUserDeviceIfNotExistsParams) (sql.Result, error) {
	return q.exec(ctx, q.insertUserDeviceIfNotExistsStmt, insertUserDeviceIfNotExists, arg.UserID, arg.DeviceID)
}
