// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertUser = `-- name: InsertUser :execresult
INSERT INTO users (id) VALUES (?)
`

func (q *Queries) InsertUser(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.exec(ctx, q.insertUserStmt, insertUser, id)
}

const upsertUser = `-- name: UpsertUser :execresult
INSERT INTO users (id) VALUES (?)
ON CONFLICT DO NOTHING
`

func (q *Queries) UpsertUser(ctx context.Context, id uuid.UUID) (sql.Result, error) {
	return q.exec(ctx, q.upsertUserStmt, upsertUser, id)
}
