services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: telemetry
    ports:
      - 5432:5432
  server:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: telemetry
      DB_SSLMODE: disable
      HTTP_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
