-- Create "devices" table
CREATE TABLE "devices" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "manufacturer" character varying NOT NULL, "model" character varying NOT NULL, "build_number" character varying NOT NULL, "os" character varying NOT NULL, "screen_width" integer NOT NULL, "screen_height" integer NOT NULL, PRIMARY KEY ("id"));
-- Create index "device_manufacturer_model_build_number" to table: "devices"
CREATE UNIQUE INDEX "device_manufacturer_model_build_number" ON "devices" ("manufacturer", "model", "build_number");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, PRIMARY KEY ("id"));
-- Create "telemetries" table
CREATE TABLE "telemetries" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "app_version" character varying NOT NULL, "os_version" character varying NOT NULL, "action_type" character varying NOT NULL, "action_data" jsonb NOT NULL, "action_at" timestamptz NOT NULL, "device_telemetries" bigint NOT NULL, "user_telemetries" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "telemetries_devices_telemetries" FOREIGN KEY ("device_telemetries") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "telemetries_users_telemetries" FOREIGN KEY ("user_telemetries") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "telemetry_app_version_user_telemetries_device_telemetries" to table: "telemetries"
CREATE INDEX "telemetry_app_version_user_telemetries_device_telemetries" ON "telemetries" ("app_version", "user_telemetries", "device_telemetries");
-- Create index "telemetry_os_version_user_telemetries_device_telemetries" to table: "telemetries"
CREATE INDEX "telemetry_os_version_user_telemetries_device_telemetries" ON "telemetries" ("os_version", "user_telemetries", "device_telemetries");
-- Create index "telemetry_user_telemetries_device_telemetries" to table: "telemetries"
CREATE INDEX "telemetry_user_telemetries_device_telemetries" ON "telemetries" ("user_telemetries", "device_telemetries");
-- Create "user_devices" table
CREATE TABLE "user_devices" ("user_id" uuid NOT NULL, "device_id" bigint NOT NULL, PRIMARY KEY ("user_id", "device_id"), CONSTRAINT "user_devices_device_id" FOREIGN KEY ("device_id") REFERENCES "devices" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_devices_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
