// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// Telemetry is the predicate function for telemetry builders.
type Telemetry func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
