// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/google/uuid"
)

type Device struct {
	ID           int64
	Manufacturer string
	Model        string
	BuildNumber  string
	Os           string
	ScreenWidth  int32
	ScreenHeight int32
}

type Telemetry struct {
	ID         int64
	UserID     uuid.UUID
	DeviceID   int64
	AppVersion string
	OsVersion  string
	Action     string
	Data       []byte
	Timestamp  interface{}
}

type User struct {
	ID uuid.UUID
}

type UserDevice struct {
	UserID   uuid.UUID
	DeviceID int64
}
