// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: telemetries.sql

package sqlc

import (
	"github.com/google/uuid"
)

type InsertTelemetriesBulkParams struct {
	UserID     uuid.UUID
	DeviceID   int64
	OsVersion  string
	AppVersion string
	Action     string
	Data       []byte
	Timestamp  interface{}
}
