// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user_devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const upsertUserDevice = `-- name: UpsertUserDevice :execresult
INSERT INTO user_devices (user_id, device_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertUserDeviceParams struct {
	UserID   uuid.UUID
	DeviceID int64
}

func (q *Queries) UpsertUserDevice(ctx context.Context, arg UpsertUserDeviceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertUserDevice, arg.UserID, arg.DeviceID)
}
