// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const upsertUser = `-- name: UpsertUser :execresult
INSERT INTO users (id) VALUES ($1)
ON CONFLICT(id) DO NOTHING
`

func (q *Queries) UpsertUser(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, upsertUser, id)
}
