// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mobile-telemetry/server/service/repo/db/entimpl/ent/device"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Device is the model entity for the Device schema.
type Device struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Manufacturer holds the value of the "manufacturer" field.
	Manufacturer string `json:"manufacturer,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// BuildNumber holds the value of the "build_number" field.
	BuildNumber string `json:"build_number,omitempty"`
	// Os holds the value of the "os" field.
	Os string `json:"os,omitempty"`
	// ScreenWidth holds the value of the "screen_width" field.
	ScreenWidth uint32 `json:"screen_width,omitempty"`
	// ScreenHeight holds the value of the "screen_height" field.
	ScreenHeight uint32 `json:"screen_height,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeviceQuery when eager-loading is set.
	Edges        DeviceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeviceEdges holds the relations/edges for other nodes in the graph.
type DeviceEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Telemetries holds the value of the telemetries edge.
	Telemetries []*Telemetry `json:"telemetries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TelemetriesOrErr returns the Telemetries value or an error if the edge
// was not loaded in eager-loading.
func (e DeviceEdges) TelemetriesOrErr() ([]*Telemetry, error) {
	if e.loadedTypes[1] {
		return e.Telemetries, nil
	}
	return nil, &NotLoadedError{edge: "telemetries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Device) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case device.FieldID, device.FieldScreenWidth, device.FieldScreenHeight:
			values[i] = new(sql.NullInt64)
		case device.FieldManufacturer, device.FieldModel, device.FieldBuildNumber, device.FieldOs:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Device fields.
func (d *Device) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case device.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case device.FieldManufacturer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field manufacturer", values[i])
			} else if value.Valid {
				d.Manufacturer = value.String
			}
		case device.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				d.Model = value.String
			}
		case device.FieldBuildNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field build_number", values[i])
			} else if value.Valid {
				d.BuildNumber = value.String
			}
		case device.FieldOs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os", values[i])
			} else if value.Valid {
				d.Os = value.String
			}
		case device.FieldScreenWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field screen_width", values[i])
			} else if value.Valid {
				d.ScreenWidth = uint32(value.Int64)
			}
		case device.FieldScreenHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field screen_height", values[i])
			} else if value.Valid {
				d.ScreenHeight = uint32(value.Int64)
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Device.
// This includes values selected through modifiers, order, etc.
func (d *Device) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Device entity.
func (d *Device) QueryUser() *UserQuery {
	return NewDeviceClient(d.config).QueryUser(d)
}

// QueryTelemetries queries the "telemetries" edge of the Device entity.
func (d *Device) QueryTelemetries() *TelemetryQuery {
	return NewDeviceClient(d.config).QueryTelemetries(d)
}

// Update returns a builder for updating this Device.
// Note that you need to call Device.Unwrap() before calling this method if this Device
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Device) Update() *DeviceUpdateOne {
	return NewDeviceClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Device entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Device) Unwrap() *Device {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Device is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Device) String() string {
	var builder strings.Builder
	builder.WriteString("Device(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("manufacturer=")
	builder.WriteString(d.Manufacturer)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(d.Model)
	builder.WriteString(", ")
	builder.WriteString("build_number=")
	builder.WriteString(d.BuildNumber)
	builder.WriteString(", ")
	builder.WriteString("os=")
	builder.WriteString(d.Os)
	builder.WriteString(", ")
	builder.WriteString("screen_width=")
	builder.WriteString(fmt.Sprintf("%v", d.ScreenWidth))
	builder.WriteString(", ")
	builder.WriteString("screen_height=")
	builder.WriteString(fmt.Sprintf("%v", d.ScreenHeight))
	builder.WriteByte(')')
	return builder.String()
}

// Devices is a parsable slice of Device.
type Devices []*Device
