// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mobile-telemetry/server/service/repo/db/entimpl/ent/predicate"
	"mobile-telemetry/server/service/repo/db/entimpl/ent/telemetry"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TelemetryDelete is the builder for deleting a Telemetry entity.
type TelemetryDelete struct {
	config
	hooks    []Hook
	mutation *TelemetryMutation
}

// Where appends a list predicates to the TelemetryDelete builder.
func (td *TelemetryDelete) Where(ps ...predicate.Telemetry) *TelemetryDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TelemetryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TelemetryDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TelemetryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(telemetry.Table, sqlgraph.NewFieldSpec(telemetry.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TelemetryDeleteOne is the builder for deleting a single Telemetry entity.
type TelemetryDeleteOne struct {
	td *TelemetryDelete
}

// Where appends a list predicates to the TelemetryDelete builder.
func (tdo *TelemetryDeleteOne) Where(ps ...predicate.Telemetry) *TelemetryDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TelemetryDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{telemetry.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TelemetryDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
