package queries

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *DeviceValueV1) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "manufacturer":
			z.Manufacturer, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Manufacturer")
				return
			}
		case "model":
			z.Model, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Model")
				return
			}
		case "build_number":
			z.BuildNumber, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BuildNumber")
				return
			}
		case "os":
			z.OS, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "OS")
				return
			}
		case "screen_width":
			z.ScreenWidth, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ScreenWidth")
				return
			}
		case "screen_height":
			z.ScreenHeight, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "ScreenHeight")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DeviceValueV1) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "manufacturer"
	err = en.Append(0x86, 0xac, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Manufacturer)
	if err != nil {
		err = msgp.WrapError(err, "Manufacturer")
		return
	}
	// write "model"
	err = en.Append(0xa5, 0x6d, 0x6f, 0x64, 0x65, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteString(z.Model)
	if err != nil {
		err = msgp.WrapError(err, "Model")
		return
	}
	// write "build_number"
	err = en.Append(0xac, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.BuildNumber)
	if err != nil {
		err = msgp.WrapError(err, "BuildNumber")
		return
	}
	// write "os"
	err = en.Append(0xa2, 0x6f, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.OS)
	if err != nil {
		err = msgp.WrapError(err, "OS")
		return
	}
	// write "screen_width"
	err = en.Append(0xac, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ScreenWidth)
	if err != nil {
		err = msgp.WrapError(err, "ScreenWidth")
		return
	}
	// write "screen_height"
	err = en.Append(0xad, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.ScreenHeight)
	if err != nil {
		err = msgp.WrapError(err, "ScreenHeight")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DeviceValueV1) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "manufacturer"
	o = append(o, 0x86, 0xac, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72)
	o = msgp.AppendString(o, z.Manufacturer)
	// string "model"
	o = append(o, 0xa5, 0x6d, 0x6f, 0x64, 0x65, 0x6c)
	o = msgp.AppendString(o, z.Model)
	// string "build_number"
	o = append(o, 0xac, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	o = msgp.AppendString(o, z.BuildNumber)
	// string "os"
	o = append(o, 0xa2, 0x6f, 0x73)
	o = msgp.AppendString(o, z.OS)
	// string "screen_width"
	o = append(o, 0xac, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68)
	o = msgp.AppendUint32(o, z.ScreenWidth)
	// string "screen_height"
	o = append(o, 0xad, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74)
	o = msgp.AppendUint32(o, z.ScreenHeight)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DeviceValueV1) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "manufacturer":
			z.Manufacturer, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Manufacturer")
				return
			}
		case "model":
			z.Model, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Model")
				return
			}
		case "build_number":
			z.BuildNumber, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BuildNumber")
				return
			}
		case "os":
			z.OS, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "OS")
				return
			}
		case "screen_width":
			z.ScreenWidth, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ScreenWidth")
				return
			}
		case "screen_height":
			z.ScreenHeight, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ScreenHeight")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DeviceValueV1) Msgsize() (s int) {
	s = 1 + 13 + msgp.StringPrefixSize + len(z.Manufacturer) + 6 + msgp.StringPrefixSize + len(z.Model) + 13 + msgp.StringPrefixSize + len(z.BuildNumber) + 3 + msgp.StringPrefixSize + len(z.OS) + 13 + msgp.Uint32Size + 14 + msgp.Uint32Size
	return
}
